[package]
name = "raynard"
version = "0.7.0"
description = "Barebones Raynard-inspired Tauri desktop chat app"
authors = ["Raynard"]
license = "MIT"
edition = "2021"

[lib]
name = "raynard_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock"] }
chrono-tz = "0.10"
dotenvy = "0.15"
futures-util = "0.3"
keyring = "4.1.5"
reqwest = { version = "0.12", features = ["json", "rustls-tls", "stream"], default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
tauri = { version = "2", features = [] }
tauri-plugin-deep-link = "2"
tauri-plugin-notification = "2"
tauri-plugin-updater = "2"
